import os
import json
import seaborn as sns
from utils.utilities import *


# GENERAL MAIN TO AUTOMATE ALL THE PIPELINE OF EXPERIMENTS

print("[SYSTEM] Forcing deterministic behavior (PYTHONHASHSEED=0)...")
os.environ["PYTHONHASHSEED"] = "0"

DATASET_FILE = "cdx-00000"
EXPECTED_SHA256 = "3D9F2F2BAEFF3DB20262B6E5580A8BA34CECBD3742D0C898B484D5ACF5C476B1"

# Graphics settings
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
plt.rcParams['font.family'] = 'serif'
plt.rcParams['pdf.fonttype'] = 42  # Ensures fonts are embedded in the PDF


# ORCHESTRATION LOGIC

def main():
    root_dir = Path(__file__).parent.resolve()
    data_dir = root_dir / "DATA"
    outputs_dir = root_dir / "Outputs"
    plots_dir = outputs_dir / "Plots"
    tables_dir = outputs_dir / "Tables"

    print("=" * 70)
    print(" GENERAL MAIN ")
    print("=" * 70)

    # 1. Setup Directories
    plots_dir.mkdir(parents=True, exist_ok=True)
    tables_dir.mkdir(parents=True, exist_ok=True)
    print(f"[SYSTEM] Output directories verified at: {outputs_dir}")

    # 2. Dataset Verification
    dataset_path = data_dir / DATASET_FILE
    if not verify_dataset_integrity(dataset_path, EXPECTED_SHA256):
        print("\n[HALT] Dataset integrity check failed. Please ensure the file is correctly")
        print("       downloaded from CC-MAIN-2024-10 and extracted in the DATA folder.")
        sys.exit(1)

    # 3. Execution of Base Benchmarks
    print("\n[ORCHESTRATOR] Delegating base benchmarks to Master Orchestrator...")
    sub_orchestrator = root_dir / "BENCHMARKS" / "master_orchestrator.py"

    if sub_orchestrator.exists():
        run_and_capture([str(python_gil), str(sub_orchestrator)],
                        "Running Base Architecture Benchmarks...", root_dir)
    else:
        print(f"[CRITICAL] Sub-Orchestrator not found at {sub_orchestrator}")
        sys.exit(1)

    # 4. Execution of I/O Stress Tests

    io_scripts = {
        "Synth_GIL_IPC": root_dir / "I_O" / "main_IO_bench_GIL.py",
        "Synth_NOGIL": root_dir / "I_O" / "main_IO_bench_NO_GIL.py",
        "Real_GIL_IPC": root_dir / "I_O" / "Real_main_IO_bench_GIL.py",
        "Real_NOGIL": root_dir / "I_O" / "Real_main_IO_bench_NO_GIL.py"
    }

    io_results = {}
    for name, script_path in io_scripts.items():
        if script_path.exists():
            interpreter = str(python_nogil) if "NO_GIL" in name else str(python_gil)
            stdout = run_and_capture([interpreter, str(script_path)], f"Running I/O Test: {name}", root_dir)
            io_results[name] = parse_io_metrics(stdout)
        else:
            print(f"[WARNING] I/O Script not found: {script_path.name}. Skipping.")

    # 4.5 Execution of Scaling Tests (Amdahl's Law etc)
    print("\n[ORCHESTRATOR] Initiating Amdahl's Law Scaling Analysis...")
    script_scal = root_dir / "BENCHMARKS" / "bench_script.py"
    scal_results = {}

    if script_scal.exists():
        # Running the script using python_nogil
        run_and_capture([str(python_nogil), str(script_scal)], "Running scaling Benchmarks...", root_dir)


        scal_json = root_dir / "BENCHMARKS" / "telemetry_bench_script.json"
        if scal_json.exists():
            with open(scal_json, 'r') as f:
                scal_results = json.load(f)
            os.remove(scal_json)  # cleaning temporary file
    else:
        print(f"[WARNING] Amdahl Script not found: {script_scal.name}. Skipping.")

    # 5. Data Aggregation and Storage (For LaTeX/Word Tables)
    print("\n[DATA EXPORT] Aggregating telemetry for Tables...")
    bench_dir = root_dir / "BENCHMARKS"

    # Reading files with names generated by parametric mode
    with open(bench_dir / "telemetry_gil_synthetic.json", 'r') as f:
        synth_gil = json.load(f)
    with open(bench_dir / "telemetry_nogil_synthetic.json", 'r') as f:
        synth_nogil = json.load(f)

    with open(bench_dir / "telemetry_gil_real.json", 'r') as f:
        real_gil = json.load(f)
    with open(bench_dir / "telemetry_nogil_real.json", 'r') as f:
        real_nogil = json.load(f)

    synth_all = {**synth_gil, **synth_nogil}
    real_all = {**real_gil, **real_nogil}

    aggregated_tables = {
        "Synthetic_Workloads": synth_all,
        "Real_Workloads": real_all,
        "IO_Stress_Tests": io_results,
        "Scaling_Laws": scal_results
    }

    tables_file = tables_dir / "Aggregated_Benchmark_Tables.json"
    with open(tables_file, 'w') as f:
        json.dump(aggregated_tables, f, indent=4)
    print(f"[DATA EXPORT] Raw table data saved to {tables_file}")

    # 6. Plot Generation
    generate_plots(synth_all, real_all, io_results, plots_dir)

    # drawing scaling plots if data exist
    if scal_results:
        # passing only specific sections to related functions
        if "Amdahl" in scal_results:
            plot_amdahl_scaling(scal_results["Amdahl"], plots_dir)

        if "Gustafson" in scal_results:
            plot_gustafson_scaling(scal_results["Gustafson"], plots_dir)

        if "Granularity" in scal_results:
            plot_chunk_optimization(scal_results["Granularity"], plots_dir)

    print("\n" + "=" * 70)
    print(" ORCHESTRATION COMPLETE. ALL DATA SECURED.")
    print("=" * 70)


if __name__ == "__main__":
    main()